* CBE20290 - Career Choices for Chemical Engineers
As you have undoubtedly already figured out, Chemical Engineering is a demanding major. Your courses will prepare you to solve complex technical problems of importance to society, to do so ethically, to work in teams, and to communicate effectively.  Those skills can take your career in an almost unlimited number of directions. This course is designed to expose you to some of those many options and to provide some of the professional skills needed to pursue them. Specifically, the learning goals of this 1 credit course are:

1. to be exposed to chemical engineering career options, through interactions with alumni who have preceeded you in this journey
2. to begin to discern options that are appealling to you
3. to develop  professional networking and presentation skills that will help get you where you want to go

* Format
The course will be conducted in person in 136 DBRT.  Weeks 1-2 will focus on professional skill development. Weeks 3-14 will involve a series of virtual panel discussions with alumni of the department. Each panel will focus on one sector, such as pharmaceuticals, energy, foods, personal care, \ldots. A group of students (you!) will introduce the topic and interview the visitors. Each of you will have a chance to participate in one of the panels.

\noindent Shared course materials available on [[https://drive.google.com/drive/folders/12p1B5icXV4FetwMoPTR7hkxTTPMj53qA?usp=sharing][Google Drive]] and on [[https://github.com/wmfschneider/CBE20290][GitHub]].

* Schedule
| January 20  | Course Introduction / [[./Resources/2022-CareerCenter-1.pdf][Career Center overview]] | [[http://linkedin.com/in/chriswashko][Chris Washko]], Career Center |
| January 27  | Career Panels Interviewing / [[./Resources/Career-Center-Networking.pdf][Networking]]      | [[https://www.linkedin.com/in/joe-plant-1ba4691/][Joe Plant]]   [[https://www.linkedin.com/in/frank-kelly-7a7109b/][Frank Kelly]]     |
| February 3  | Alumni Panel: Professional/Grad School       | student interviewer team    |
| February 10 | Alumni Panel: Oil & Gas                      | student interviewer team    |
| February 17 | Alumni Panel: Foods                          | student interviewer team    |
| February 24 | Alumni Panel: Chemicals                      | student interviewer team    |
| March 3     | Alumni Panel: Pharmaceuticals                | student interviewer team    |
| March 10    | Alumni Panel: Consumer Goods                 |                             |
| March 17    | Spring Break                                 |                             |
| March 24    | Alumni Panel: Entrepreneurship               | student interviewer team    |
| March 31    | Alumni Panel: Consulting                     | student interviewer team    |
| April 7     | Good Friday                                  |                             |
| April 14    | Alumni Panel: Biotech                        | student interviewer team    |
| April 21    | Alumni Panel: Info Tech                      | student interviewer team    |
| April 28    | Alumni Panel: Energy/Renewable               | student interviewer team    |

* Assignments 
| Due January 18 | [[https://forms.gle/395K9j9xREVQg88NA][Career Reflection]]   |     |
| Due January 25 | [[https://forms.gle/fRgPeqDvfJ78tRaY9][Interview Questions]] |     |
| Rolling basis  | [[./Assignments/Interview.org][Career Panel]]        | [[./Assignments/Interview.pdf][pdf]] |
| Due May 5      | [[https://forms.gle/GjdNjfbhfEXnvLEF6][Final Reflection]]    |     |

* Grading
The course is graded S/U. To receive an S, you must complete all assignments.

* Mental Health
Care and Wellness Consultants provide support and resources to students who are experiencing stressful or difficult situations that may be interfering with academic progress. Through Care and Wellness Consultants, students can be referred to The University Counseling
Center (for cost-free and confidential psychological and psychiatric services from
licensed professionals), University Health Services (which provides primary care,
psychiatric services, case management, and a pharmacy), and The McDonald
Center for Student Well Being (for problems with sleep, stress, and substance
use). Visit [[https://care.nd.edu]].

* Professional courtesy
1. Arrive at each session on time, early if possible.
2. Turn your camera on. Make sure you are sitting up and acting professionally.
3. Dress appropriately. 
4. Research the organization, the presenters’ backgrounds, or industries. Be prepared!
5. You can ask questions through the chat or by unmuting yourself. Participate!
6. Say thank you...by unmuting yourself or following up with the alumni/speaker in an email.

