#+BEGIN_OPTIONS
#+AUTHOR: William F. Schneider
#+TITLE: CBE 20290 Career Panel
#+EMAIL: wschneider@nd.edu
#+LATEX_CLASS_OPTIONS: [11pt]
#+LATEX_HEADER:\usepackage[left=1in, right=1in, top=1in, bottom=1in, nohead]{geometry}
#+LATEX_HEADER:\geometry{margin=1.0in}
#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{parskip}
#+LATEX_HEADER:\usepackage{graphicx}
#+LATEX_HEADER:\usepackage{framed,color}
#+LATEX_HEADER:\usepackage{epstopdf}
#+LATEX_HEADER:\usepackage{fancyhdr}
#+LATEX_HEADER:\usepackage{hyperref}
#+LATEX_HEADER:\usepackage[labelfont=bf]{caption}
#+LATEX_HEADER:\usepackage{setspace}
#+LATEX_HEADER:\setlength{\headheight}{10.2pt}
#+LATEX_HEADER:\setlength{\headsep}{20pt}
#+LATEX_HEADER:\def\dbar{{\mathchar'26\mkern-12mu d}}
#+LATEX_HEADER:\pagestyle{fancy}
#+LATEX_HEADER:\fancyhf{}
#+LATEX_HEADER:\renewcommand{\headrulewidth}{0.5pt}
#+LATEX_HEADER:\renewcommand{\footrulewidth}{0.5pt}
#+LATEX_HEADER:\lfoot{\today}
#+LATEX_HEADER:\cfoot{\copyright\ 2023 W.\ F.\ Schneider}
#+LATEX_HEADER:\rfoot{\thepage}
#+LATEX_HEADER:\chead{\bf{Career Choices for Chemical Engineers (CBE 20290)\vspace{12pt}}}
#+LATEX_HEADER:\lhead{\bf{Career Panels}}
#+LATEX_HEADER:\rhead{\bf{January 25, 2023}}
#+LATEX_HEADER:\usepackage{titlesec}
#+LATEX_HEADER:\titlespacing*{\section}
#+LATEX_HEADER:{0pt}{0.6\baselineskip}{0.2\baselineskip}
#+LATEX_HEADER:\title{University of Notre Dame\\Career Choices\\(CBE 20290)}
#+LATEX_HEADER:\author{Prof. William F.\ Schneider}
#+LATEX_HEADER:\def\dbar{{\mathchar'26\mkern-12mu d}}
#+LATEX_HEADER:\usepackage{siunitx}

#+OPTIONS: toc:nil
#+OPTIONS: H:3 num:3
#+OPTIONS: ':t
#+END_OPTIONS

** Organization
The weekly alumni career panels are intended to expose you to the diverse career paths taken by chemical engineers and  the diverse fields in which their skills can be applied in. They also provide an opportunity to practice your presentation and interviewing skills through interactions with alumni and current professionals.

Each session, one group of 3-4 students will be responsible for managing the panel discussion, including introductions, questions and answers, and written summary. The topical areas, panelists, and your assigned groups are available on a [[https://docs.google.com/spreadsheets/d/1UrQxN718aKtfRA056bWFxMjVzuaijhqmwvEfHE7_juQ/edit?usp=sharing][Google sheet]] accessible from your ND account.  The Google sheet contains the email addresses and LinkedIn links of all the panelists and the student members of each group.

** Panel agenda and tasks:
1. Introduce yourselves
2. Present a brief (2-3  minute, 2-3 slides) summary of the topical area
3. Present a brief (30 seconds, 1 slide) introduction of each panelist
4. Interview and moderate discussion with the panelists 
5. Write a brief summary of the panel discussion

To do this well will take some preparation. I suggest the team meet to set some roles and responsibilities.  Agree on individual roles:
- Background on the field 
- Introduce speaker 1 
- Introduce speaker 2
- Introduce speaker 3
- Timer/wrap-up/thank you

And work together on group roles:
- Questions/interview format
- Panel reflection
- Post-panel thank you to panelists

You will want to contact the panelists ahead of time to obtain some biographical information, and the group will need to do research to describe the nature of the field (what services/produced does it provide, what is the size of the area, who are major players).

The group will also want to prepare a set of questions, or script, to guide the discussion with the speakers. You can draw from the [[https://docs.google.com/document/d/1xEKQUh8swVG-FaPlv5Zdm7GvCSkyAsRE-FH6ohEHZMg/edit?usp=sharing][questions you prepared in Assignment 2]]. The panel time is short, so think carefully about the topics you would like to cover. Try to avoid the routine ("what is your typical day like?"); rather, seek to learn about the field, unique experiences of the panelists, and advice. Use good interviewing skills. Each group member should  contribute to the interviewing. 


** Logistics
Place your introductory slides in the class [[https://drive.google.com/drive/folders/1r_wSSi8Jvphhkkfh8ujKThlI-RCvBMRM?usp=share_link][Google folder]] by noon Friday of your panel session. Come to the classroom with your laptop charged, at least 15 minutes before class starts, in business casual dress.  Each panel member will sign into the class [[https://notredame.zoom.us/j/92948211493?pwd=WU1nbCt4S3MwOHdxM245Rm5pWXFFZz09][zoom link]], and the panelists will be projected to the classroom. You or the instructor will share the slides while you present them, followed by your interview of the panel. Use good *active listen skills*: summarize answers, and ask follow ups.

** Panel Reflection
After the panel, take a few minutes to reflect. What went well with the panel? What might you have done differently? What did you learn that was surprising or unexpected (if nothing, you weren't asking probing questions!). As a group, using Google docs, prepare a brief (1 page) reflection addressing these points. Sign it as a group. Place your written summary into the same folder by 8 am Monday following your session. 

** Graciousness
Remember that the alumni are knowledgeable and eager to help you. Remember too that they are taking valuable time out of their day. Be well prepared, dress appropriately, be courteous, and be grateful. 

#+BEGIN_COMMENT

|-------------+------------------+-------------------------+------------------------+-----------------|
| Date        | Topic            |                         | Panelists              |                 |
|-------------+------------------+-------------------------+------------------------+-----------------|
| 26-Feb-2021 | Pharmaceuticals  | [[mailto:smckenzi16@gmail.com][Shane McKenzie]]          | [[mailto:rose-marie.mazanek@lilly.com][Rose-Marie Mazanek]]     | [[mailto:sgpk242@gmail.com][Sean Keenan]]     |
|             |                  | [[mailto:Catherine.drummond@takeda.com][Catherine Drummond]]      |                        |                 |
|             |                  |                         |                        |                 |
| 5-Mar-2021  | Consumer/health  | [[mailto:cackley713@gmail.com][Catherine Ackley]]        | [[mailto:delacoterac@gmail.com][Cristian de la Cotera]]  | [[mailto:Aminnis1@gmail.com][Alie Minnis]]     |
|             | products         | [[mailto:mshakall@gmail.com][Mirian Shakalli]]         |                        |                 |
|             |                  |                         |                        |                 |
| 12-Mar-2021 | Biotechnology    | Thomas Eyster           | Adam Farchone          | Jessica Freeman |
|             |                  | Andrew Ayoob            |                        |                 |
|             |                  |                         |                        |                 |
| 19-Mar-2021 | Energy &         | Connor Tomshack         | Nick O'Neill           | Jeff Ulrich     |
|             | Renewables       | Timothy Politano        |                        |                 |
|             |                  |                         |                        |                 |
| 26-Mar-2021 | Oil & Gas        | Marcella Smith          | Laura Stangler Sigward | David Zadigian  |
|             |                  | Allison Hamman          |                        |                 |
|             |                  |                         |                        |                 |
| 9-Apr-2021  | Chemicals        | Clare Tennant           | Gabriel Janer          | Luis Lazalde    |
|             |                  | Caitlin O'Connell       |                        |                 |
|             |                  |                         |                        |                 |
| 16-Apr-2021 | Foods            | Rocio Miramontes Hamlin | Alexander Augugliaro   | Amy Rizzo       |
|             |                  |                         |                        |                 |
|             |                  |                         |                        |                 |
| 23-Apr-2021 | Professional/    | Hunter Smith            | Michael Comuniello     | Adam Mallette   |
|             | Grad School      |                         |                        |                 |
|             |                  |                         |                        |                 |
| 30-Apr-2021 | Information Tech | Clay Elmore             | Ross Verploegh         | Matthew High    |
|             |                  |                         |                        |                 |
|             |                  |                         |                        |                 |
| 7-May-2021  | Entrepreneurship | Gary Nijak              | Jeffrey Racho          | Ed Redden       |
|             |                  |                         |                        |                 |
|             |                  |                         |                        |                 |
|-------------+------------------+-------------------------+------------------------+-----------------|



The first  


The objective of this course is to become familiar with multiple different fields of employment for post graduation.  I will assign 5-6 students to a group based on your collective shared interests. Each week, there will be a panel discussion with 4 Alumnis from the Notre Dame Chemical Engineering department. Each group will be responsible for a panel one week. During your group's week, you will be responsible for drafting questions, introducing the speakers, and making a transcript of the answers. Below you will find a breakdown of the roles. 

Students: 
Background on the field 
Introduce speaker 1 
Introduce speaker 2
Introduce speaker 3
Introduce speaker 4
Possible sixth group member will provide additional information as needed 

This section of the project is individual, where each member is in charge of a different aspect of the introduction to the panel. The student responsible for background on the field will do a short review of what the field entails that the speakers are coming from. This can include descriptions, explanations, and options that you have researched. The students responsible for introducing the various speakers will be in charge of contacting the panelists and gathering some basic information on who they are, when they graduated from Notre Dame, what their current field of employment is, etc. Please note that each student should speak for around 30 seconds in providing background information or introducing a speaker. 

All students in the group must work together to provide the following: 
A script of questions to ask the panel members 
All group members must equally participate in asking questions 
A written transcript of the panel 
Please write this in a Q/A format 

Example: 
Q: What resource did you find most useful in narrowing your career options? 
A: I spent a lot of time talking with professors, alumnus, and professionals in the field to discern where my interests were. 

Please write out the transcript in this format, which will later be shared with the class as review. It is also important to note that the questions used for the script can come from the compilation of questions students have come up with, which has been provided to you. 


replace. Tab to end.
#+END_COMMENT

